server:
  port: :3033

worker:
  pool: 100
  idle: 30

postgres:
  Driver: postgres
  Host: localhost
  User: root
  Password: root
  DBName: restaurant-report
  Port: 5432
  SSLMode: disable

rabbitmq:
  URI: amqp://%s:%s@localhost:5672/
  user: guest
  password: guest

databus:
  consumer:
    exchangeType: direct
    contentType: application/json

branch:
  consumer:
    exchangeType: direct
    contentType: application/json
  pdf:
    path: /Users/cesardelgadom/Documentos/go/projects/restaurant-report/pdf_generated/  
    suffix: -branches-report.pdf
    font: Arial
    title: Report Branches
