server:
  port: :3033

worker:
  pool: 100
  idle: 30

postgres:
  Driver: postgres
  Host: localhost
  User: root
  Password: root
  DBName: restaurant-report
  Port: 5432
  SSLMode: disable

rabbitmq:
  URI: amqp://%s:%s@localhost:5672/
  user: guest
  password: guest

databus:
  consumer:
    exchangeType: direct
    contentType: application/json

smtp:
  gmail:
    client: smtp.gmail.com
    port: 587
    email: reports473@gmail.com
    password: hwiw lprg aifa vegz

branch:
  consumer:
    exchangeType: direct
    contentType: application/json
  pdf:
    path: /Users/cesardelgadom/Documentos/go/projects/restaurant-report/pdf_generated/  
    suffix: -branches-report.pdf
    font: Arial
    title: Report Branches
  notification:
    success: 
      subject: Branch report - 
      body: Hi, your report is ready!
    failed:
      subject: Branch report failed -
      body: Hi, the branch report failed the generation, sorry!
